### ISSUE TITLE
Superiorblock2 - Border 

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SuperiorSkyblock2-RhinoEngine#1]
### Minecraft's Version

1.17.1

### Plugin's Version

![image](https://user-images.githubusercontent.com/105610066/173941176-b6b3500b-3fe7-4eeb-989d-de28aa55422e.png)

### Describe the bug

Island border is not displayed

### To Reproduce

-

### Additional Information

Something strange happened, I tried to remove the island / create from scratch and there was still no border, none of the players can see border now (it worked earlier)

I tried every option here and unfortunately it does not appear at all (I turned on / off the border) and restarted the server

![image](https://user-images.githubusercontent.com/105610066/173941208-43fe8cf0-ea6c-46be-a1d3-d298c00ade0a.png)

**Comment by OmerBenGera** [comment]
Open the issue under the plugin itself:
https://github.com/BG-Software-LLC/SuperiorSkyblock2
